parameters:
# nothing to declare

services:
  _defaults:
    autowire: true

  LeoVie\PhpMethodModifier\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpCleanCodeBundle.php'

  _instanceof:
    LeoVie\PhpMethodModifier\Model\AccessModifier\AccessModifier:
      tags: [ 'app.access_modifier' ]

  LeoVie\PhpMethodModifier\Model\AccessModifier\AccessModifierCollection:
    arguments: [ !tagged_iterator { tag: 'app.access_modifier' } ]

  LeoVie\PhpMethodModifier\Service\ModifyMethodService:
    public: true